### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by GabrielleTse** [THU-DA-6D-Pose-Group/GDR-Net#52]
We implement the training process with pbr rendered data on eight GPU parallel computing (NIVDIA 2080 Ti with graphic memory of 12 G) , it barely starts training in batchsize 8 (original is 24). But when we resume the training process, CUDA will be out of memory. 

We'd like to know the author's training configuration...

**Comment by wangg12** [comment]
Hello, I usually train the model using a single 2080Ti GPU (11G).

**Comment by GabrielleTse** [comment]
Thank you very much for your fast and kind reply! However, we're still facing the same issue with multiple 2080Ti GPUs. My concerns are now:

1. The rendered pbr data for LM-O is around 200G, the "CUDA out of memory" warning arises only when we train real+pbr. Is the size of pbr data correct? Is it possible that something wrong in pbr data rendering?

![b3c184289b1baa94bc7cbb35ec88945](https://user-images.githubusercontent.com/37495877/142985066-64b108b5-d74f-45af-b5a7-0d3de2ca70cf.png)

2. We find that here are 8 sub-functions running on each GPU, is there any .py file controlling the function parallel computing, so that we can reduce the configuration?

![3f2d185650f9c8d0ddc14a895195e8b](https://user-images.githubusercontent.com/37495877/142985464-bf10b508-f00c-4dd3-bbcc-d3d2f3bb8b82.png)

**Comment by wangg12** [comment]
For training on multiple gpus with ddp, it seems that the workers in the dataloader will create many subprocesses which occupy a lot of gpu memory. I don't know how to solve this problem and I almost always train the models using a single GPU. Maybe there are some hidden bug in the current implementation for training on multiple gpus with ddp. 
If anyone can solve the problem, please do let me know.

**Comment by GabrielleTse** [comment]
We've fixed the problem by changing the training configuration file:
[https://github.com/THU-DA-6D-Pose-Group/GDR-Net/blob/main/configs/_base_/common_base.py](url)

# -----------------------------------------------------------------------------
# DataLoader
# -----------------------------------------------------------------------------
DATALOADER = dict(
    # Number of data loading threads
    NUM_WORKERS=4,
    ……
)

NUM_WORKERS controls the number of processes distributed on GPUs, when we reduce 
NUM_WORKERS=4 
into 
NUM_WORKERS=3

CUDA won't be out of memory on multiple GPUs.

**Comment by wangg12** [comment]
Try the updated code, the memory issue caused by ddp spawn should be resolved.
